[workspace]
resolver = "2"

members = [
    "axorigin",
    "axstd",
    "axruntime",
    "axhal",
    "axconfig",
    "axalloc",
    "axsync",
    "axtask",
    "axlog",
    "page_table",
    "crate_interface",
    "bitmap-allocator",
]

[profile.release]
lto = true
