[workspace]
resolver = "2"

members = [
    "axorigin",
    "axstd",
    "axruntime",
    "axhal",
    "axconfig",
    "axalloc",
    "axsync",
    "page_table",
    "crate_interface",
]

[profile.release]
lto = true
