[package]
name = "page_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axconfig =  { path = "../axconfig" }
log = "0.4"
